Repository openWB/openwb-ui-settings, pull requests merged in 2024-07, with the labels that each got.

#510 Fix install assistant
  src/components/backup_clouds/samba/backup_cloud.vue
  src/components/install_assistant/InstallAssistantStep0.vue
  src/components/install_assistant/InstallAssistantStep1.vue
  src/components/install_assistant/InstallAssistantStep9.vue
  src/router/index.js
  src/views/DataManagement.vue
Labels: bug, enhancement

#512 fix samba backup cloud folder validation
  src/components/backup_clouds/samba/backup_cloud.vue
Labels: bug

#520 Feature cards display theme
  src/components/display_themes/cards/displayTheme.vue
Labels: enhancement, core

#517 setting http api
  src/views/GeneralConfig.vue
Labels: enhancement, core

#483 Feature chart improvements
  src/views/Chart.vue
Labels: enhancement
