Repository openWB/openwb-ui-settings, pull requests merged in 2024-09, with the labels that each got.

#539 modify label of phase switch timing slider
  src/views/GeneralChargeConfig.vue
Labels: enhancement

#543 improve helptext for Deye and GoodWe
  src/components/devices/deye/device.vue
  src/components/devices/good_we/device.vue
Labels: enhancement

#525 Solaredge external inverter
  src/components/devices/solaredge/external_inverter.vue
Labels: enhancement, core

#546 Systembericht-Angaben Issue:#101. Systembericht mit zusätzlichen Daten vorbelegen #101
  src/views/HardwareInstallation.vue
  src/views/Support.vue
  src/views/VehicleConfig.vue
Labels: enhancement

#557 Dependencies
  package-lock.json
  src/components/backup_clouds/BackupCloudConfigMixin.vue
  src/components/backup_clouds/OpenwbBackupCloudProxy.vue
  src/components/backup_clouds/onedrive/backup_cloud.vue
  src/components/charge_points/OpenwbChargePointProxy.vue
  src/components/devices/OpenwbConfigProxy.vue
  src/components/display_themes/OpenwbDisplayThemeProxy.vue
  src/components/electricity_tariffs/OpenwbElectricityTariffProxy.vue
  src/components/ripple_control_receivers/OpenwbRippleControlReceiverProxy.vue
  src/components/vehicles/OpenwbVehicleProxy.vue
  src/components/web_themes/OpenwbWebThemeProxy.vue
Labels: dependencies
