Repository openWB/openwb-ui-settings, pull requests merged in 2024-01, with the labels that each got.

#401 updated dependencies
  package-lock.json
Labels: dependencies

#397 Feature electricity tariff
  src/components/OpenwbBaseTextInput.vue
  src/components/electricity_tariffs/OpenwbElectricityTariffConfigFallback.vue
  src/components/electricity_tariffs/OpenwbElectricityTariffProxy.vue
  src/components/electricity_tariffs/awattar/electricity_tariff.vue
  src/components/electricity_tariffs/tibber/electricity_tariff.vue
  src/components/electricity_tariffs/voltego/electricity_tariff.vue
  src/components/status/ElectricityTariffCard.vue
  src/views/GeneralChargeConfig.vue
  src/views/GeneralConfig.vue
  src/views/Status.vue
  src/views/VehicleConfig.vue
Labels: core

#404 Charts - energy source datasets
  src/views/Chart.vue
Labels: core

#407 Persistent Logging for data migration
  src/views/DebugConfig.vue
Labels: enhancement, core
