Repository openWB/openwb-ui-settings, pull requests merged in 2024-05, with the labels that each got.

#457 #rfid hide field if not activated
  src/views/ChargePointInstallation.vue
  src/views/VehicleConfig.vue
Labels: bug

#458 Bugfix
  package-lock.json
  package.json
  src/components/__tests__/OpenwbBaseButtonGroupInput.spec.js
  src/components/devices/solax/device.vue
  src/views/VehicleConfig.vue
Labels: bug, dependencies

#461 device Tasmota configuration UI
  src/components/devices/tasmota/counter.vue
  src/components/devices/tasmota/device.vue
Labels: enhancement
