Repository openWB/openwb-ui-settings, pull requests merged in 2024-04, with the labels that each got.

#433 UI fixes
  jsconfig.json
  package-lock.json
  package.json
  src/components/debug_config/LogCard.vue
  src/components/devices/fronius/counter_sm.vue
  src/components/devices/fronius/inverter_secondary.vue
  src/components/vehicles/evcc/vehicle.vue
  src/views/CloudConfig.vue
  src/views/DebugConfig.vue
Labels: enhancement, dependencies

#432 Implementierung_Einrichtungsassistent unter System->Einrichtungsassis
  src/App.vue
  src/components/OpenwbPageNavbar.vue
  src/router/index.js
  src/store/index.js
  src/views/InstallAssistant.vue
Labels: enhancement, core

#438 Filter versions
  src/views/System.vue
Labels: enhancement, core

#429 Enphase: Serial number in config dialog
  src/components/devices/enphase/device.vue
Labels: enhancement, core

#455 remove outdated error topic
  src/components/OpenwbPageCommandAlert.vue
  src/components/OpenwbPageMessages.vue
Labels: bug, core

#456 Fixes
  src/components/OpenwbBaseButtonGroupInput.vue
  src/views/DataManagement.vue
  src/views/GeneralConfig.vue
  src/views/HardwareInstallation.vue
  src/views/LoadManagementConfig.vue
  src/views/PVChargeConfig.vue
Labels: enhancement
