Repository openWB/openwb-ui-settings, pull requests merged in 2025-03, with the labels that each got.

#658 fix topic subscription
  src/components/status/ChargePointCard.vue
Labels: bug

#653 UPower
  src/components/devices/upower/upower/device.vue
Labels: enhancement, core

#647 OctopusEnergy
  src/components/electricity_tariffs/octopusenergy/electricity_tariff.vue
Labels: enhancement, core

#661 percentage for imported counters
  src/views/Chart.vue
Labels: enhancement, core

#655 add host validation patterns
  src/components/OpenwbBaseTextInput.vue
Labels: enhancement

#668 Io fixes
  src/components/electricity_tariffs/ostrom/electricity_tariff.vue
  src/components/io_actions/controllable_consumers/dimming_direct_control/io_action.vue
  src/components/io_actions/controllable_consumers/ripple_control_receiver/io_action.vue
  src/components/io_actions/generator_systems/power_levels/io_action.vue
  src/components/status/IoDeviceCard.vue
Labels: enhancement

#666 soc-module VWId: add link to Wiki
  src/components/vehicles/vwid/vehicle.vue
Labels: documentation

#665 soc-module OVMS: add link to Wiki
  src/components/vehicles/ovms/vehicle.vue
Labels: documentation

#656 soc_bmwbc: add description for secondary vehicles
  src/components/vehicles/bmwbc/vehicle.vue
Labels: documentation, core

#650 soc_vwid: add calculate_soc option
  src/components/vehicles/vwid/vehicle.vue
Labels: enhancement, core

#627 Feature fixed hour tariff
  src/components/electricity_tariffs/fixed_hours/FixedTariff.vue
  src/components/electricity_tariffs/fixed_hours/TimeRow.vue
  src/components/electricity_tariffs/fixed_hours/TimeTable.vue
  src/components/electricity_tariffs/fixed_hours/electricity_tariff.vue
  src/views/GeneralChargeConfig.vue
Labels: enhancement, core

#612 Enhance LogCard.vue with log file selection and clipboard copy functionality
  package-lock.json
  package.json
  src/components/OpenwbBaseCard.vue
  src/components/debug_config/LogCard.vue
Labels: enhancement

#659 Add nibe config
  public/modules/legacy_smart_home/smarthomeconfig.php
Labels: enhancement, core

#675 Feature enhanced log card
  package-lock.json
  package.json
  src/components/OpenwbBaseCard.vue
  src/components/debug_config/LogCard.vue
Labels: enhancement

#662 chart command
  src/views/Chart.vue
Labels: bug, core

#679 regular npm updates
  .github/workflows/node.js.yml
  package-lock.json
  package.json
Labels: dependencies
