Repository openWB/openwb-ui-settings, pull requests merged in 2025-01, with the labels that each got.

#613 fix sungrow firmware naming
  src/components/devices/sungrow/sungrow/device.vue
Labels: bug, core

#616 fix empty files in yearly download
  public/downloadChargeLog.php
Labels: bug

#617 fix sungrow firmware selection
  src/components/devices/sungrow/sungrow/device.vue
Labels: bug

#623 Updated dependencies
  package-lock.json
  src/components/devices/ampere/ampere/device.vue
  src/components/devices/huawei/huawei/device.vue
  src/components/status/ChargePointCard.vue
  src/components/vehicles/psacc/vehicle.vue
  src/views/ChargeLog.vue
  src/views/PVChargeConfig.vue
Labels: dependencies

#622 Add config page for colors display theme
  src/components/display_themes/colors/displayTheme.vue
Labels: enhancement

#619 don't show preconfigured options in UI, linting
  src/components/devices/benning/benning/inverter.vue
  src/components/devices/opendtu/opendtu/inverter.vue
Labels: enhancement
