Repository openWB/openwb-ui-settings, pull requests merged in 2025-04, with the labels that each got.

#686 add configurable power limit controllable for mqtt bat components
  src/components/devices/generic/mqtt/bat.vue
Labels: enhancement, core

#687 fix algodue settings
  src/components/devices/algodue/algodue/counter.vue
  src/components/devices/algodue/algodue/device.vue
Labels: bug

#683 fix sorting of branch tags
  src/views/System.vue
Labels: bug

#693 Feature standard web theme
  src/components/web_themes/koala/webTheme.vue
  src/views/VehicleConfig.vue
Labels: enhancement

#558 adopt file check on restore
  public/uploadFile.php
  src/views/DataManagement.vue
Labels: enhancement, core

#697 fix nextcloud backup input type
  src/components/backup_clouds/nextcloud/backup_cloud.vue
Labels: bug

#667 Leaf config
  src/components/vehicles/leaf/vehicle.vue
Labels: enhancement, core

#703 SonnenBatterie: bugfix
  src/components/devices/sonnen/sonnenbatterie/counter_consumption.vue
Labels: bug

#705 updated dependencies
  package-lock.json
  package.json
  src/components/vehicles/leaf/vehicle.vue
Labels: dependencies
